### ISSUE TITLE
Problem compiling with GCC, clash with "string"

### ISSUE THREAD

**Issue by carmichaelong** [tgeijten/xo#6]
Output from compiler:
![image](https://user-images.githubusercontent.com/7455790/56757398-f0fe1380-6748-11e9-87d8-f2cc1b2e3e81.png)

Looks like the issue is that `<string>` has a typedef for `string`, and then the compiler gets confused with the function name `string()`. @tgeijten Any thoughts on how to fix this without renaming the function?

**Comment by tgeijten** [comment]
Changing the return type to const xo::string& should solve the problem. Alternatively, const std::string& is also fine.

**Comment by tgeijten** [comment]
const std::string& is actually better for compatibility with std::filesystem.

**Comment by carmichaelong** [comment]
I tried the `const xo::string&` return about a week ago too when I thought it was the return type clashing, but it generates the same compiler error. I just tried `const std::string&`, but it returns the same error too:
![image](https://user-images.githubusercontent.com/7455790/56826822-012df580-6812-11e9-8b52-97df3b5b306e.png)

**Comment by tgeijten** [comment]
That's weird... Looks like a bug in GCC. For now, can you rename the method to "const string& str()?" I'll try and find a better solution later (after I manage to install Linux on my machine).

**Comment by carmichaelong** [comment]
This is the most relevant post and smallest case I've seen. It looks like GCC has a different stance on this than the Clang, MSVC, etc.
https://stackoverflow.com/questions/15537023/declaration-of-method-changes-meaning-of-symbol

**Comment by tgeijten** [comment]
Thanks for looking into this. This seems to be a different issue though, since the string typedef is not inside the xo::path scope. Also, it doesn't explain why std::filesystem::path::string() doesn't have the same problem 😕.

For now, have your tried renaming to str()? I can also do it -- just let me know so we don't do it both.

**Comment by tgeijten** [comment]
Nevermind -- I already did the rename (it's safer that way because I also use it in other projects). Could you update to the latest version and verify if the error is fixed?

**Comment by carmichaelong** [comment]
Looks like the error with string() vs str() is fixed now. However, another issue with `path` has come up. See screenshot below (this is only a short snippet, as you can imagine the errors keep going to cover probably everything in the `path` class):
![image](https://user-images.githubusercontent.com/7455790/56914071-fff60600-6a67-11e9-8fae-9283e5cc97b3.png)

Maybe this points out a larger scope issue? I'm happy to test some quick ideas today if you have any leads, and I can do more detailed debugging starting tomorrow afternoon too.
